name: "Validate contributing workspace"

on:
  push:
    branches:
    - master
    - develop

jobs:
  docker-build:
    name: Build Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create empty env
        run: cp .env.example .env

      - name: Log in to GitHub Packages
        run: docker login docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin <<< "${DOCKER_PASSWORD}"
        env:
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull images
        run: docker-compose pull
        continue-on-error: true

      - name: Build images
        run: docker-compose build

      - name: Upload images
        run: docker-compose push
  validate-composer:
    name: Validate contribute command
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4
          extensions: exif, json, mbstring, bcmath, dom, fileinfo, mysql, gd, imagick
          coverage: none

      - name: Run Contribute command
        run: composer run contribute

      - name: Validate result
        run: |
          test -f .env
          curl -s -o /dev/null -D- -m 5 http://localhost:13370


